name: Build pypdu macOS & Linux (Python3.10)
on: push
jobs:
  build-manylinux-3_10:
    name: Build manylinux (Python3.10)
    runs-on: ubuntu-latest
    env:
        CIBW_BUILD: 'cp310*x86_64'
        CIBW_MANYLINUX_X86_64_IMAGE: "jamesharrisoncb/manylinux2014_x86_64_conan"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: build wheels
        uses: pypa/cibuildwheel@v2.1.1
      - uses: actions/upload-artifact@v2
        with:
            name: manylinux-3_10
            path: wheelhouse/*.whl
  build-mac-3_10:
    name: Build mac (Python3.10)
    runs-on: macos-10.15
    env:
        CIBW_BUILD: 'cp310*x86_64'
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Set up Python 3 for Conan
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.17.x'
      - name: Install Python packages
        run: pip3 install conan setuptools wheel
      - name: Add conancenter remote
        run: conan remote add -f conancenter https://center.conan.io
      - name: build wheels
        uses: pypa/cibuildwheel@v2.1.1
      - uses: actions/upload-artifact@v2
        with:
            name: mac-3_10
            path: wheelhouse/*.whl
