name: Publish Python distributions to PyPI and TestPyPI
on:
  pull_request:
    branches:
      - "*"

jobs:

  build-manylinux-3_X:
    name: Build manylinux wheels (Python3.X)
    runs-on: ubuntu-22.04
    env:
        CIBW_BUILD: '{cp,pp}3*manylinux*x86_64'
        CIBW_SKIP: '{cp,pp}3{6,7}*'
        CIBW_MANYLINUX_X86_64_IMAGE: "jameseh96/manylinux2014_x86_64_vcpkg"
        CIBW_MANYLINUX_PYPY_X86_64_IMAGE: "jameseh96/manylinux2014_x86_64_vcpkg"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: build wheels
        uses: pypa/cibuildwheel@v2.21.1
      - uses: actions/upload-artifact@v4
        with:
            name: manylinux-3_X
            path: wheelhouse/*.whl
  upload:
    name: Publish to PyPI
    runs-on: ubuntu-22.04
    needs: [build-manylinux-3_X]
    steps:
      - name: Create ./dist
        run: mkdir ./dist
      - uses: actions/download-artifact@v4
        with:
            name: manylinux-3_X
            path: dist
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
